.base: &base
  forwardAgent: true
  multiplexing: true

159.223.56.55: &dev1
  <<: *base
  stage: "develop"
  user: "root"
  port: 22
  identityFile: "C:/Users/phamt/.ssh/server-key"
  deploy_path: "/var/www/{{application}}"
  branch: "develop"
