<script type="text/javascript" src="{{asset('/js/jquery-v3.5.1.min.js')}}"></script>
<script type="text/javascript" src="{{asset('/js/jquery-UI-v1.12.1.min.js')}}"></script>
<script type="text/javascript" src="{{asset('/js/dataTables-v1.10.21.min.js')}}"></script>
<script type="text/javascript" src="{{asset('/js/dataTables-v1.10.21.bootstrap4.min.js')}}"></script>
<script type="text/javascript" src="{{asset('/js/dataTables.responsive.min.js')}}"></script>
<script type="text/javascript" src="{{asset('/js/responsive.bootstrap4.min.js')}}"></script>
<script type="text/javascript" src="{{asset('/js/popper.min.js')}}"></script>
<script type="text/javascript" src="{{asset('/js/bootstrap-v4.5.min.js')}}"></script>
<script type="text/javascript" src="{{asset('/js/jquery-ui.js')}}"></script>
<script type="text/javascript" src="{{asset('/js/moment.js')}}"></script>
<script type="text/javascript" src="{{asset('/js/move-top.js')}}"></script>
<script type="text/javascript" src="{{asset('/js/easing.js')}}"></script>
<script type="text/javascript" src="{{asset('/js/toastr-v2.1.3.min.js')}}"></script>
<script type="text/javascript" src="{{asset('/js/typeahead.js')}}"></script>
<script type="text/javascript" src="{{asset('/js/toggle-bt4.min.js')}}"></script>
<script type="text/javascript" src="{{asset('/js/daterangepicker.min.js')}}"></script>
<script type="text/javascript" src="{{asset('/js/home/script.js')}}"></script>
<script type="text/javascript" src="{{asset('/js/home/script-form.js')}}"></script>
